/**
 * Eventos da timeline do lead (docs/DATABASE.md §4.4). Os payloads guardam ids,
 * tipos e valores mascarados, nunca dados pessoais em claro: a timeline é
 * append-only e não pode depender de anonimização posterior.
 */
export const LEAD_EVENTS = {
  created: 'lead.created',
  updated: 'lead.updated',
  archived: 'lead.archived',
  unarchived: 'lead.unarchived',
  ownerAssigned: 'owner.assigned',
  personAdded: 'person.added',
  personUpdated: 'person.updated',
  personRemoved: 'person.removed',
  contactPointAdded: 'contact_point.added',
  contactPointUpdated: 'contact_point.updated',
  contactPointRemoved: 'contact_point.removed',
  noteAdded: 'note.added',
  noteRemoved: 'note.removed',
  tagAdded: 'tag.added',
  tagRemoved: 'tag.removed',
  permissionChanged: 'permission.changed',
  optOutRegistered: 'optout.registered',
  suppressionRevoked: 'suppression.revoked',
  anonymized: 'lead.anonymized',
  originAdded: 'origin.added',
  merged: 'lead.merged',
  mergedInto: 'lead.merged_into',
  stageChanged: 'stage.changed',
  scoreChanged: 'score.changed',
  taskCreated: 'task.created',
  taskCompleted: 'task.completed',
  activityLogged: 'activity.logged',
  messageSent: 'message.sent',
  messageReceived: 'message.received',
  socialComment: 'social.comment',
  replyClassified: 'reply.classified',
  cadenceEnrolled: 'cadence.enrolled',
  cadencePaused: 'cadence.paused',
  cadenceResumed: 'cadence.resumed',
  cadenceStopped: 'cadence.stopped',
  cadenceCompleted: 'cadence.completed',
  handoffCreated: 'handoff.created',
  opportunityAccepted: 'opportunity.accepted',
  opportunityWon: 'opportunity.won',
  opportunityLost: 'opportunity.lost',
} as const;

export type LeadEventType = (typeof LEAD_EVENTS)[keyof typeof LEAD_EVENTS];

export const LEAD_EVENT_LABELS: Record<LeadEventType, string> = {
  'lead.created': 'Lead cadastrado',
  'lead.updated': 'Dados alterados',
  'lead.archived': 'Lead arquivado',
  'lead.unarchived': 'Lead reativado',
  'owner.assigned': 'Responsável alterado',
  'person.added': 'Pessoa adicionada',
  'person.updated': 'Pessoa alterada',
  'person.removed': 'Pessoa removida',
  'contact_point.added': 'Contato adicionado',
  'contact_point.updated': 'Contato alterado',
  'contact_point.removed': 'Contato removido',
  'note.added': 'Observação adicionada',
  'note.removed': 'Observação removida',
  'tag.added': 'Tag adicionada',
  'tag.removed': 'Tag removida',
  'permission.changed': 'Base legal ou opt-in alterado',
  'optout.registered': 'Opt-out registrado',
  'suppression.revoked': 'Item da Lista Não Contatar revogado',
  'lead.anonymized': 'Lead anonimizado',
  'origin.added': 'Encontrado em nova origem',
  'lead.merged': 'Lead mesclado com outro',
  'lead.merged_into': 'Lead mesclado em outro',
  'stage.changed': 'Etapa alterada',
  'score.changed': 'Score alterado',
  'task.created': 'Tarefa criada',
  'task.completed': 'Tarefa concluída',
  'activity.logged': 'Atividade registrada',
  'message.sent': 'Mensagem enviada',
  'message.received': 'Resposta recebida',
  'social.comment': 'Comentou no Instagram da Docline',
  'reply.classified': 'Resposta classificada',
  'cadence.enrolled': 'Inscrito na cadência',
  'cadence.paused': 'Cadência pausada',
  'cadence.resumed': 'Cadência retomada',
  'cadence.stopped': 'Cadência encerrada',
  'cadence.completed': 'Cadência concluída sem resposta',
  'handoff.created': 'Transferido ao Comercial',
  'opportunity.accepted': 'Transferência aceita pelo Comercial',
  'opportunity.won': 'Oportunidade ganha',
  'opportunity.lost': 'Oportunidade perdida',
};
